version: '3.4'

services:
  daemon:
    image: beademingstoestel/daemon
    volumes: 
      - pid:/pid
    depends_on:
      - mongo
      - interface
    environment:
      - SERIAL_PORT=/dev/ventilator
      - MONGO_HOST=mongo
      - INTERFACE_HOST=interface
    devices:
      - "/dev/ventilator:/dev/ventilator"
    restart: always 
  interface:
    image: beademingstoestel/interface
    ports:
      - 3001:3001
    volumes: 
      - pid:/pid
    depends_on:
      - mongo
    restart: always  
  mongo:
    image: beademingstoestel/mongo
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - pid:/pid
volumes: 
  pid:
    
